export const WORDLE_HOW_TO_PLAY =
  "Guess the five-letter word in six tries. Each guess gives feedback: green for correct letters in the right spot, yellow for correct letters in the wrong spot, and gray for incorrect letters. Use these hints to refine your guesses and solve the puzzle.";

export const GAME_LOST = "Sorry! You've lost. The correct answer was: ";
export const GAME_WON = "Congratulations! You've guessed the correct answer in";
export const NUM_OF_TRIES = 6;
export const WORD_LENGTH = 5;

export const WORDS = [
  "AGENT",
  "WORLD",
  "ABOUT",
  "HEART",
  "WATER",
  "SIXTY",
  "BOARD",
  "MONTH",
  "MUSIC",
  "PARTY",
  "PIANO",
  "MOUTH",
  "WOMAN",
  "SUGAR",
  "AMBER",
  "DREAM",
  "LAUGH",
  "TIGER",
  "EARTH",
  "MONEY",
  "WORDS",
  "SMILE",
  "LEMON",
  "SOUTH",
  "AFTER",
  "STONE",
  "THING",
  "LIGHT",
  "STORY",
  "POWER",
  "TODAY",
  "RANGE",
  "PEARL",
  "VENOM",
  "PROXY",
  "ROUND",
  "HOVER",
  "CANDY",
  "ABOVE",
  "PHONE",
  "OTHER",
  "SMART",
  "BLACK",
  "MAGIC",
  "FRUIT",
  "RADIO",
  "ROYAL",
  "HONEY",
  "FLAKE",
  "SOUND",
];
